name: 'Generate data🧭'
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v*'

jobs:
  data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Generate talents
        run: deno task talent

      - name: Generate itemset
        run: deno task itemset

      - name: Generate glyph
        run: deno task glyph

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: Update data files'
