name: "Locale addon 🌏"
on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "v*"

jobs:
  locale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: DengSir/curse-locale-action@master
        with:
          token: ${{ secrets.CURSE_TOKEN }}

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: Update locale files'
