name: Publish 🚛
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Publish to curseforge
        uses: curse-action/publish@master
        with:
          curse-wow-token: ${{ secrets.CURSE_TOKEN }}

      - name: Release to github
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelog.txt
          files: |
            *.zip

      - name: Release to gitee
        uses: nicennnnnnnlee/action-gitee-release@v1.0.5
        with:
          gitee_owner: DengSir
          gitee_repo: ${{ github.repository }}
          gitee_token: ${{ secrets.GITEE_TOKEN }}
          gitee_tag_name: ${{ github.ref }}
          gitee_release_name: ${{ github.ref }}
          gitee_release_notes: "https://github.com/DengSir/${{ github.repository }}/releases/tag/${{ github.ref }}"
          gitee_upload_retry_times:  3
          gitee_files: |
            *.zip
